### ISSUE TITLE
Error when generating a new dungeon world thru console

### ISSUE THREAD

**Issue by sgdc3** [timvisee/DungeonMaze#33] opened 2015-03-16 21:52 UTC
https://gist.github.com/sgdc3/d6e9e2d4700ffbec20f4

**Comment by timvisee** [comment] 2015-03-17 01:42
Thanks for posting the error. It does seem to be something that could be easily fixed, but that will be something to do for tomorrow.

Tim Visée

**Comment by timvisee** [comment] 2015-03-28 16:55
Hello,

I couldn't reproduce the error occurring thus I've tried to fix it based on the error log even though I can't really debug it properly. The bug is possibly fixed in the following commit:
https://github.com/timvisee/DungeonMaze/commit/2e546366ebe06135b6ac382326845f650024ca15

It would be great if you could try whether the bug has been fixed in the latest snapshot. If it doesn't seem to be fixed, please open (or re-open) a new issue.

Tim Visée

**Closed** 2015-03-28 16:55 UTC
Labels: bug

**Comment by sgdc3** [comment] 2015-03-28 20:08
Fixed ;)

**Comment by timvisee** [comment] 2015-03-28 23:53
Brilliant. Thanks for the quick response.

Tim Visée
